# Generated by Django 5.2.11 on 2026-02-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("body", models.TextField(help_text="Write your message here.")),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "All Active Members"),
                            ("officers", "Officers Only"),
                            ("guests", "Guests Only"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
