# Generated by Django 5.2.11 on 2026-06-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="body",
            field=models.TextField(
                help_text="Write your message here. Markdown is supported (**bold**, *italic*, [links](https://…), - lists) along with emojis and the {first_name} placeholder."
            ),
        ),
    ]
