# Generated by Django 5.2.11 on 2026-08-12 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0002_alter_announcement_body"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="recipients",
            field=models.ManyToManyField(
                blank=True,
                help_text="Used only when the audience is “Selected Members”. Unlike the predefined audiences, guests can be picked here.",
                related_name="announcements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="audience",
            field=models.CharField(
                choices=[
                    ("all", "All Active Members"),
                    ("officers", "Officers Only"),
                    ("guests", "Guests Only"),
                    ("selected", "Selected Members"),
                ],
                default="all",
                max_length=20,
            ),
        ),
    ]
