# Generated by Django 5.2.11 on 2026-02-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("theme", models.CharField(blank=True, max_length=200)),
                ("word_of_the_day", models.CharField(blank=True, max_length=50)),
                ("zoom_link", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="MeetingRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_speech_role", models.BooleanField(default=False)),
                (
                    "points",
                    models.IntegerField(
                        default=1, help_text="Points for difficulty/effort"
                    ),
                ),
            ],
        ),
    ]
