# Generated by Django 5.2.11 on 2026-02-06 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0003_attendance"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "default_roles",
                    models.ManyToManyField(
                        related_name="meeting_types", to="meetings.role"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="meeting",
            name="meeting_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="meetings.meetingtype",
            ),
        ),
    ]
