# Generated by Django 5.2.11 on 2026-02-06 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0004_meetingtype_meeting_meeting_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="meetingrole",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="meetingtype",
            name="default_roles",
        ),
        migrations.AddField(
            model_name="meetingrole",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="MeetingTypeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=1, help_text="How many of this role?"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in the agenda"
                    ),
                ),
                (
                    "meeting_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="meetings.meetingtype",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="meetings.role"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
