# Generated by Django 5.2.11 on 2026-02-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0005_alter_meetingrole_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingrole",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Speech title, project details, or feedback."
            ),
        ),
    ]
