# Generated by Django 5.2.11 on 2026-02-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0006_meetingrole_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingrole",
            name="admin_notes",
            field=models.TextField(
                blank=True,
                help_text="Private feedback or details for the follow-up email.",
            ),
        ),
    ]
