# Generated by Django 5.2.11 on 2026-02-08 13:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0007_meetingrole_admin_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meetingrole",
            name="backup_user",
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("meeting", "user"),
                name="unique_member_attendance",
            ),
        ),
    ]
