# Generated by Django 5.2.11 on 2026-02-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0008_remove_meetingrole_backup_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingtypeitem",
            name="default_note",
            field=models.TextField(
                blank=True,
                help_text="Pre-filled note for this role when a meeting is created.",
            ),
        ),
    ]
