# Generated by Django 5.2.11 on 2026-02-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0008_remove_meetingrole_backup_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingtype",
            name="agenda_template",
            field=models.FileField(
                blank=True,
                help_text="Word (.docx) template for this meeting type's agenda. Leave blank to use the default.",
                upload_to="agenda_templates/",
            ),
        ),
    ]
