# Generated by Django 5.2.11 on 2026-02-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0009_add_default_note_to_meetingtypeitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="in_person",
            field=models.BooleanField(
                default=True, help_text="Uncheck for roles that can be done remotely"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="time_minutes",
            field=models.PositiveIntegerField(
                default=0, help_text="Expected duration in minutes"
            ),
        ),
    ]
