# Generated by Django 5.2.11 on 2026-02-11 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0010_add_time_and_in_person_to_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Expected duration in minutes"
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "takes_roles",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck for breaks or segments that don't have assigned roles",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeetingTypeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in the agenda"
                    ),
                ),
                (
                    "meeting_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="meetings.meetingtype",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meetings.session",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="meetingtypeitem",
            name="meeting_type_session",
            field=models.ForeignKey(
                blank=True,
                help_text="Which session this role belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="meetings.meetingtypesession",
            ),
        ),
        migrations.AddField(
            model_name="meetingrole",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="meetings.session",
            ),
        ),
    ]
