# Generated by Django 5.2.11 on 2026-02-11 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0011_add_session_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meetingtypeitem",
            name="meeting_type_session",
        ),
        migrations.AddField(
            model_name="meetingtypeitem",
            name="session",
            field=models.ForeignKey(
                blank=True,
                help_text="Which session this role belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="meetings.session",
            ),
        ),
    ]
