# Generated by Django 5.2.11 on 2026-02-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0012_replace_meetingtypesession_fk_with_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="note",
        ),
        migrations.AddField(
            model_name="meetingtypesession",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
