# Generated by Django 5.2.11 on 2026-02-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0014_add_meeting_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingrole",
            name="in_person",
            field=models.BooleanField(
                default=True, help_text="Uncheck for roles done remotely"
            ),
        ),
        migrations.AddField(
            model_name="meetingrole",
            name="time_minutes",
            field=models.PositiveIntegerField(
                default=0, help_text="Expected duration in minutes"
            ),
        ),
    ]
