# Generated by Django 5.2.11 on 2026-02-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0015_meetingrole_in_person_meetingrole_time_minutes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="guest_name",
        ),
        migrations.AddField(
            model_name="attendance",
            name="guest_first_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="attendance",
            name="guest_last_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
