# Generated by Django 5.2.11 on 2026-02-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0016_split_guest_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingtype",
            name="zoom_link",
            field=models.URLField(blank=True),
        ),
    ]
