# Generated by Django 5.2.11 on 2026-05-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0017_add_zoom_link_to_meeting_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingrole",
            name="in_person",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Whether the assigned member attends in person. Null until a member signs up.",
                null=True,
            ),
        ),
    ]
