# Generated by Django 5.2.11 on 2026-05-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0018_alter_meetingrole_in_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingrole",
            name="pathways_level",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                help_text="Pathways level 1–5.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="meetingrole",
            name="pathways_path",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Dynamic Leadership", "Dynamic Leadership"),
                    ("Effective Coaching", "Effective Coaching"),
                    ("Engaging Humor", "Engaging Humor"),
                    ("Innovative Planning", "Innovative Planning"),
                    ("Leadership Development", "Leadership Development"),
                    ("Motivational Strategies", "Motivational Strategies"),
                    ("Persuasive Influence", "Persuasive Influence"),
                    ("Presentation Mastery", "Presentation Mastery"),
                    ("Strategic Relationships", "Strategic Relationships"),
                    ("Team Collaboration", "Team Collaboration"),
                    ("Visionary Communication", "Visionary Communication"),
                ],
                help_text="Toastmasters Pathways path the member is working (speech roles).",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="meetingrole",
            name="pathways_project",
            field=models.CharField(
                blank=True,
                help_text="Pathways project name for this speech.",
                max_length=200,
            ),
        ),
    ]
