# Generated by Django 5.2.11 on 2026-05-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "meetings",
            "0019_meetingrole_pathways_level_meetingrole_pathways_path_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingtypeitem",
            name="in_person",
            field=models.BooleanField(
                default=True,
                help_text="Whether this role is expected to be performed in person at this meeting type. Used as the dialog default at sign-up; members can override.",
            ),
        ),
    ]
