# Generated by Django 5.2.11 on 2026-05-23 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0021_copy_role_in_person_to_meetingtypeitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="in_person",
        ),
    ]
