# Generated by Django 5.2.11 on 2026-05-24 01:08

import django.db.models.deletion
from django.db import migrations, models


# Existing Role names that should be flagged as evaluator roles. Anything
# not in this list keeps the default is_evaluator_role=False.
EVALUATOR_ROLE_NAMES = (
    "Evaluator (Speech)",
    "Evaluator (Rant)",
    "Evaluator (Table Topic)",
    "General Evaluator",
)


def flag_existing_evaluator_roles(apps, schema_editor):
    Role = apps.get_model("meetings", "Role")
    Role.objects.filter(name__in=EVALUATOR_ROLE_NAMES).update(is_evaluator_role=True)


def unflag_evaluator_roles(apps, schema_editor):
    Role = apps.get_model("meetings", "Role")
    Role.objects.filter(name__in=EVALUATOR_ROLE_NAMES).update(is_evaluator_role=False)


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0022_remove_in_person_from_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingrole",
            name="evaluates",
            field=models.ForeignKey(
                blank=True,
                help_text="For an evaluator role, the MeetingRole this evaluator is evaluating (must be on the same meeting).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluators",
                to="meetings.meetingrole",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="is_evaluator_role",
            field=models.BooleanField(
                default=False,
                help_text="Marks roles that evaluate a speech, rant, or table-topics session. Used to filter admin dropdowns for MeetingRole.evaluates.",
            ),
        ),
        migrations.RunPython(
            flag_existing_evaluator_roles, unflag_evaluator_roles
        ),
    ]
