# Generated by Django 5.2.11 on 2026-05-24 17:13

from django.db import migrations, models


# Existing Role names that should be flagged as evaluated roles. Anything
# not in this list keeps the default is_evaluated_role=False.
EVALUATED_ROLE_NAMES = ("Speaker", "Ranter")


def flag_existing_evaluated_roles(apps, schema_editor):
    Role = apps.get_model("meetings", "Role")
    Role.objects.filter(name__in=EVALUATED_ROLE_NAMES).update(is_evaluated_role=True)


def unflag_evaluated_roles(apps, schema_editor):
    Role = apps.get_model("meetings", "Role")
    Role.objects.filter(name__in=EVALUATED_ROLE_NAMES).update(is_evaluated_role=False)


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0023_add_evaluator_pairing"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="is_evaluated_role",
            field=models.BooleanField(
                default=False,
                help_text="Marks roles that get evaluated by an evaluator role (e.g. Speaker, Ranter). Used as the target-side filter for MeetingRole.evaluates.",
            ),
        ),
        migrations.RunPython(
            flag_existing_evaluated_roles, unflag_evaluated_roles
        ),
    ]
