# Generated by Django 5.2.11 on 2026-05-27 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_role_guide_log(apps, schema_editor):
    """Pre-populate one RoleGuideEmailLog row for every distinct (user, role)
    pair already present in MeetingRole. Members who have *already* taken a
    role shouldn't get a "first time" email retroactively when an officer
    uploads a guidance PDF for that role later.
    """
    MeetingRole = apps.get_model("meetings", "MeetingRole")
    RoleGuideEmailLog = apps.get_model("meetings", "RoleGuideEmailLog")
    pairs = (
        MeetingRole.objects.filter(user__isnull=False)
        .values_list("user_id", "role_id")
        .distinct()
    )
    RoleGuideEmailLog.objects.bulk_create(
        [RoleGuideEmailLog(user_id=uid, role_id=rid) for uid, rid in pairs],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0025_rename_is_speech_role_to_shows_pathways_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="guidance_document",
            field=models.FileField(
                blank=True,
                help_text="Attached to the welcome email a member receives the first time they take this role. Leave blank to skip the email.",
                null=True,
                upload_to="role_guides/",
            ),
        ),
        migrations.CreateModel(
            name="RoleGuideEmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="meetings.role"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_guide_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "role"),
                        name="unique_role_guide_email_per_user_role",
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_role_guide_log, migrations.RunPython.noop),
    ]
