# Generated by Django 5.2.11 on 2026-05-28 10:59

from django.db import migrations, models
from django.db.models import F, Q
from django.utils import timezone


def backfill_feedback_sent(apps, schema_editor):
    """Mark every existing role's notes and every existing guest as
    already-sent. Under the old behavior the feedback button re-sent on every
    click, so these were presumably already emailed; without this backfill the
    new idempotency check would treat them as never-sent and blast them once
    more. Officers re-send only by editing the notes afterward.
    """
    MeetingRole = apps.get_model("meetings", "MeetingRole")
    Attendance = apps.get_model("meetings", "Attendance")

    MeetingRole.objects.exclude(admin_notes="").update(
        feedback_sent_notes=F("admin_notes")
    )
    Attendance.objects.filter(
        Q(user__is_guest=True) | Q(user__isnull=True, guest_email__gt="")
    ).update(thank_you_sent_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0026_add_role_guidance_and_email_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="thank_you_sent_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="When the guest thank-you email was last sent. Null until sent; keeps repeated feedback runs from re-thanking a guest.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="meetingrole",
            name="feedback_sent_notes",
            field=models.TextField(
                blank=True,
                default="",
                editable=False,
                help_text="The admin_notes content last emailed as feedback. Lets the feedback button send once per member, then re-send only when the notes are edited.",
            ),
        ),
        migrations.RunPython(backfill_feedback_sent, migrations.RunPython.noop),
    ]
