# Generated by Django 5.2.11 on 2026-05-28 11:29

from django.db import migrations, models


def hide_president_from_agenda(apps, schema_editor):
    """Preserve prior behavior: the President row was hidden on the web agenda
    via a hardcoded name match. Replace that with the new flag for any existing
    role named "President"."""
    Role = apps.get_model("meetings", "Role")
    Role.objects.filter(name="President").update(show_on_agenda=False)


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0027_attendance_thank_you_sent_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="show_on_agenda",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to keep this role off the published agenda (web page and Word download) and the sign-up page, e.g. President.",
            ),
        ),
        migrations.RunPython(hide_president_from_agenda, migrations.RunPython.noop),
    ]
