# Generated by Django 5.2.11 on 2026-06-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0029_role_duration_range"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingtype",
            name="zoom_meeting_id",
            field=models.CharField(
                blank=True,
                help_text="Numeric Zoom meeting ID (e.g. 81234567890) used for the attendance/registrant API. Not derivable from the registration URL.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="meetingtype",
            name="zoom_link",
            field=models.URLField(
                blank=True,
                help_text="Public Zoom registration URL (members register here, then Zoom emails them a personal join link). Shown on the agenda and in the 'register' reminder.",
            ),
        ),
    ]
