# Generated by Django 5.2.11 on 2026-06-16 13:21

from django.db import migrations, models


def backfill_meeting_zoom_id(apps, schema_editor):
    """Seed each existing meeting's zoom_meeting_id from its meeting type, so
    the new per-meeting field matches the type-level value already in use."""
    Meeting = apps.get_model("meetings", "Meeting")
    for meeting in (
        Meeting.objects.filter(zoom_meeting_id="")
        .exclude(meeting_type__isnull=True)
        .select_related("meeting_type")
    ):
        type_id = meeting.meeting_type.zoom_meeting_id
        if type_id:
            meeting.zoom_meeting_id = type_id
            meeting.save(update_fields=["zoom_meeting_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0030_meetingtype_zoom_meeting_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="zoom_meeting_id",
            field=models.CharField(
                blank=True,
                help_text="Numeric Zoom meeting ID for this meeting's link, used for attendance/registrant API calls. Keep in sync with the link above.",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            backfill_meeting_zoom_id, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="meeting",
            name="zoom_link",
            field=models.URLField(
                blank=True, help_text="Public Zoom registration URL members click."
            ),
        ),
    ]
