# Generated by Django 5.2.11 on 2026-06-25 10:47

from django.db import migrations, models


def set_general_evaluator_flag(apps, schema_editor):
    """The General Evaluator appears twice on the agenda but is held by one
    member, so it's the canonical single-holder role."""
    Role = apps.get_model("meetings", "Role")
    Role.objects.filter(name="General Evaluator").update(
        single_holder_all_slots=True)


def unset_general_evaluator_flag(apps, schema_editor):
    Role = apps.get_model("meetings", "Role")
    Role.objects.filter(name="General Evaluator").update(
        single_holder_all_slots=False)


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0032_fix_meeting_times_to_eastern"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="single_holder_all_slots",
            field=models.BooleanField(
                default=False,
                help_text="When True, one member fills every slot of this role in a meeting at once: signing up for any slot claims the others, and dropping or editing one updates them all (e.g. General Evaluator, who appears at two points in the agenda).",
            ),
        ),
        migrations.RunPython(
            set_general_evaluator_flag, unset_general_evaluator_flag
        ),
    ]
