# Generated by Django 5.2.11 on 2026-07-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0033_role_single_holder_all_slots"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingrole",
            name="in_person",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Attendance mode for this slot. Seeded from the meeting type's planned mode; a member may override it at sign-up. Null only when the slot has no template default.",
                null=True,
            ),
        ),
    ]
