# Generated by Django 5.2.11 on 2026-08-12 10:33

import meetings.models
from django.db import migrations, models


def scatter_kiosk_tokens(apps, schema_editor):
    """Give every existing meeting its own token.

    AddField evaluates the callable default once and writes that single value
    to every existing row, which would hand all past meetings a shared token.
    """
    Meeting = apps.get_model("meetings", "Meeting")
    for meeting in Meeting.objects.all().only("id"):
        Meeting.objects.filter(pk=meeting.pk).update(
            kiosk_token=meetings.models.generate_kiosk_token()
        )


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0034_add_co_timer_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kiosk", "Kiosk / QR check-in"),
                    ("admin", "Entered in admin"),
                    ("import", "Imported"),
                ],
                help_text="How this attendance record was created.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="kiosk_token",
            field=models.CharField(
                default=meetings.models.generate_kiosk_token,
                editable=False,
                help_text="Scopes anonymous kiosk access to this meeting. Rotates per meeting; carried in the QR code URL.",
                max_length=32,
            ),
        ),
        migrations.RunPython(scatter_kiosk_tokens, migrations.RunPython.noop),
    ]
