"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv
from import_export.formats.base_formats import CSV


# Load variables from .env
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-insecure-)%@r1uqdg_sn*w9if2yy_qxi#h2c74pw^qkfqnui&=2y$*1q7x"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

# Distinguish between debugging and deploying
DEPLOY = os.getenv("DEPLOY", "False") == "True"


# Allowed hosts
if not DEPLOY:
    ALLOWED_HOSTS = []
else:
    # Expected by Railway
    ALLOWED_HOSTS = ["*"]

    # Trust requests coming from your Railway URL.
    # Replace the string below if you use a custom domain.
    csrf_trusted = os.getenv("CSRF_TRUSTED_ORIGINS", "")
    if csrf_trusted:
        CSRF_TRUSTED_ORIGINS = csrf_trusted.split(",")
    else:
        # Fallback: Trust all Railway subdomains (Wildcard)
        CSRF_TRUSTED_ORIGINS = ["https://*.railway.app", "https://*.up.railway.app"]

    # 2. PROXY SSL HEADER (Fixes Redirect Loops & Security Checks)
    # Railway terminates SSL at the load balancer. This tells Django:
    # "If the header says HTTPS, trust that it is HTTPS."
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party
    "django_htmx",
    "import_export",
    "anymail",
    # Local Apps (The SpeakUp Architecture)
    "core",
    "members",
    "meetings",
    "education",
    "communications",
]


# Add WhiteNoise to middleware for collecting static files
# Add HTMX to middleware for frontend interactivity
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
]

ROOT_URLCONF = "config.urls"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "core" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Email configuration for development
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Email configuration for production
# DATABASES = {
#     "default": dj_database_url.config(default="sqlite:///db.sqlite3", conn_max_age=600)
# }


# Set the custom user model
AUTH_USER_MODEL = "members.User"

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"  # Where files go in production
# Prevent the "No directory" crash on Railway
if DEPLOY and not os.path.exists(STATIC_ROOT):
    os.makedirs(STATIC_ROOT)

    # Enable Whitenoise storage for production
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Ensure CSV is the default import and export format
IMPORT_EXPORT_FORMATS = [CSV]

# Email configuration for development
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# EMAIL_HOST_USER = "officers@speakup.com"  # Default "From" address

# Email configuration for production
EMAIL_BACKEND = "anymail.backends.brevo.EmailBackend"
BREVO_API_KEY = os.getenv("BREVO_API_KEY")
ANYMAIL = {
    "BREVO_API_KEY": BREVO_API_KEY,
}
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@speakup.com")
SERVER_EMAIL = DEFAULT_FROM_EMAIL  # Error messages come from here
