# Generated by Django 5.2.11 on 2026-05-23 14:06

from django.db import migrations, models
from django.db.models.functions import Lower


def lowercase_emails(apps, schema_editor):
    """Lowercase every existing User.email before applying unique=True.

    The unique constraint is case-sensitive at the DB level, but
    ``User.save()`` lowercases emails going forward. Normalizing existing
    rows here makes the constraint behave case-insensitively in practice
    against the data already in the table.
    """
    User = apps.get_model("members", "User")
    User.objects.exclude(email="").exclude(email=Lower("email")).update(
        email=Lower("email")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_seed_officers_group"),
    ]

    operations = [
        migrations.RunPython(lowercase_emails, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
